name: rest-mvc-app

services:
  mysql:
    extends:
      file: db/compose.db.yml
      service: mysql-base

  rest-app:
    image: cadebe/spring-6-rest-mvc:latest
    environment:
      - PROFILE=${PROFILE}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/restdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    depends_on: [ mysql ]
    ports:
      - '8080:8080'

volumes:
  mysql-db:
