name: rest-mvc-app

services:
  mysql:
    image: rest-mvc-mysql
    build:
      context: ..
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_PORT=${MYSQL_PORT}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-db:/var/lib/mysql

  rest-app:
    image: cadebe/spring-6-rest-mvc:latest
    environment:
      - PROFILE=${PROFILE}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/restdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    depends_on: [ mysql ]
    ports:
      - '8080:8080'

volumes:
  mysql-db:
