spring:
  flyway:
    enabled: false

#  jpa:
#    properties:
#      jakarta:
#        persistence:
#          schema-generation:
#            scripts:
#              action: 'drop-and-create'
#              create: 'metadata'
#              drop-target: 'drop-and-create.sql'
#              create-target: 'drop-and-create.sql'

springdoc:
  api-docs:
    path: '/api-docs'

beer:
  service:
    page-limit: 1250
    default-page-size: 35

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics
  elastic:
   metrics:
    export:
      host: http://localhost:9200
      enabled: true

info:
  java-version: ${java.specification.version}

logging:
  level:
    dev:
      cadebe: debug