spring:

  datasource:
    username: restadmin
    password: password
    url: 'jdbc:mysql://127.0.0.1:3306/restdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC'
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    hikari:
      pool-name: 'RestDB-Pool'
      maximum-pool-size: 5
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

  flyway:
    enabled: true

  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true # show SQL
        format_sql: true # format SQL

springdoc:
  api-docs:
    path: '/api-docs'


logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind:
              trace
