name: 'rest-mvc'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql

volumes:
  mysql-db: