# This workflow will test and build the Java project with Maven.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: 'CI | Java Maven build'

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ $default-branch ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/spring-6-rest-mvc:latest

jobs:
  build:
    name: Build project
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      checks: write

    steps:

      - name: Checkout code from repository ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build the application with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify

      - name: Test reporting
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: '**/target/surefire-reports/TEST-*.xml,**/target/failsafe-reports/TEST-*.xml'
          reporter: java-junit
          fail-on-error: true

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          file: ./docker/Dockerfile
          push: false
          load: true # Export to Docker Engine rather than pushing to a registry
          tags: ${{ env.IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Run Trivy for all CVEs (non-blocking)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE }}
          format: table
          exit-code: 0

      - name: Run Trivy for HIGH,CRITICAL CVEs and report (blocking)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE }}
          exit-code: 1
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Docker build and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          file: ./docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' && github.ref_name == 'main' }}
          labels: ${{ env.IMAGE }}
          tags: ${{ env.IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
